### PR TITLE
Fix Unicode escapes and empty strings parsing

### PR DESCRIPTION
**Pull request by kwikwag**
The logic was reversed in the code that validates that the Unicode escape sequence ("\uXXXX") is long enough. Also, the wrong offset was pushed forward.

### CODE REVIEW

**Comment by kwikwag** [comment]
Hmm, after some testing I see that Unicode escape aren't parsed properly either. I'll add some more commits soon to fix this as well.

**Comment by sheredom** [comment]
Hey @kwikwag - thanks for the PR!

Is there any chance you could add a test or two for the problems you found? It'll help make sure I'd never accidentally regress something for you in future!

**Comment by kwikwag** [comment]
I also added a fix where empty strings were handled incorrectly. And corresponding tests. Should be good to go.

**Comment by sheredom** [comment]
Nice! Thanks for all the work :)

**Pull request merged**
